### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_file'

### ISSUE THREAD

**Issue by Maerzig** [kha-white/mokuro#111]
When running Mokuro on a single file I always seem to get the following error:

At first I thought this might be some weird issue with the way I installed it (I'm on Arch Linux and since there's no package for Mokuro I opted to install it via pip through a venv), so I booted up my Windows partition and installed it on there as well but I seem to get the same error.   
I tried a few Python versions on Windows as well but only 3.8 seemed to not cause dependency issues with pytorch, so that is what got me this error as well.  
If there's any more info needed, please let me know.  

```Traceback (most recent call last):
  File "/home/alex/.mokuro/bin/mokuro", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alex/.mokuro/lib/python3.12/site-packages/mokuro/__main__.py", line 7, in main
    fire.Fire(run)
  File "/home/alex/.mokuro/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.mokuro/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.mokuro/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/.mokuro/lib/python3.12/site-packages/mokuro/run.py", line 94, in run
    vc.add_path_in(path_in)
  File "/home/alex/.mokuro/lib/python3.12/site-packages/mokuro/volume.py", line 147, in add_path_in
    volume = self.volumes[path_mokuro] = Volume(path_in)
                                         ^^^^^^^^^^^^^^^
  File "/home/alex/.mokuro/lib/python3.12/site-packages/mokuro/volume.py", line 70, in __init__
    if self.path_mokuro.is_file():
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_file' ```

**Comment by martinbarez** [comment]
Mokuro processes images in a folder (or zip/cbz archives), not pdf files. When I used mokuro for the first time I made that mistake and I remember getting a similar, if not the same error.

**Comment by Maerzig** [comment]
@martinbarez I absolutely misunderstood how to use Mokuro. I was trying to have it process pdf files, not realizing that I needed images in a folder.
Works perfectly now, thank you for the help!
