### ISSUE TITLE
Failed to install package via pip

### ISSUE THREAD

**Issue by fernandofleury** [kha-white/mokuro#32]
Hiya, I'm trying to run the project on python `3.9.13` and am getting the following error:

```
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rz/d266t0dn1md992kgv7z8tp480000gn/T/pip-install-mxoysvv8/fugashi_621defc0e8774e36a8d22bd2f46c3d4a/setup.py", line 15, in <module>
          output, data_files = check_libmecab()
        File "/private/var/folders/rz/d266t0dn1md992kgv7z8tp480000gn/T/pip-install-mxoysvv8/fugashi_621defc0e8774e36a8d22bd2f46c3d4a/fugashi_util.py", line 58, in check_libmecab
          raise RuntimeError("Could not configure working env. Have you installed MeCab?")
      RuntimeError: Could not configure working env. Have you installed MeCab?
      [end of output]
```

**Comment by matchai** [comment]
I ran into the same issue, whichin my case, seemed to be caused by me running an macOS ARM machine.
It seems `fugashi` doesn't yet directly support Apple Silicon.

That said, it seems to work as expected if you separately install `mecab` via Homebrew before installing mokuro:
```
brew install mecab
pip3 install mokuro
```
