### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'register_load_context_function'

### ISSUE THREAD

**Issue by alexander-kohler** [kha-white/mokuro#42]
I get this error when trying to run it

```
Traceback (most recent call last):
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\Scripts\mokuro.exe\__main__.py", line 4, in <module>
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\mokuro\__init__.py", line 3, in <module>
    from mokuro.manga_page_ocr import MangaPageOcr
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\mokuro\manga_page_ocr.py", line 8, in <module>
    from manga_ocr import MangaOcr
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\manga_ocr\__init__.py", line 3, in <module>
    from manga_ocr.ocr import MangaOcr
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\manga_ocr\ocr.py", line 8, in <module>
    from transformers import AutoFeatureExtractor, AutoTokenizer, VisionEncoderDecoderModel
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\__init__.py", line 469, in <module>
    _keras._load()
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\models\__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\functional.py", line 34, in <module>
    from keras.engine import training as training_lib
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 45, in <module>
    from keras.saving.legacy import save
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\legacy\save.py", line 24, in <module>
    from keras.saving.legacy.saved_model import load_context
  File "C:\Users\xelak\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\legacy\saved_model\load_context.py", line 68, in <module>
    tf.__internal__.register_load_context_function(in_load_context)
AttributeError: module 'tensorflow.compat.v2.__internal__' has no attribute 'register_load_context_function'
```

**Comment by kha-white** [comment]
Closing as stale, let me know if you still have this problem
