### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by novastar88** [kha-white/mokuro#93]
OS: Windows 10
Python: 3.12.2
pip upgraded to latest
error occuring on every usage of mokuro, in this case "mokuro" in cmd

`
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Scripts\mokuro.exe\__main__.py", line 4, in <module>
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\mokuro\__init__.py", line 3, in <module>
    from mokuro.manga_page_ocr import MangaPageOcr, InvalidImage
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\mokuro\manga_page_ocr.py", line 7, in <module>
    from comic_text_detector.inference import TextDetector
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\comic_text_detector\inference.py", line 11, in <module>
    from comic_text_detector.basemodel import TextDetBase, TextDetBaseDNN
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\comic_text_detector\basemodel.py", line 9, in <module>
    from comic_text_detector.models.yolov5.yolo import load_yolov5_ckpt
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\comic_text_detector\models\yolov5\yolo.py", line 4, in <module>
    from comic_text_detector.utils.yolov5_utils import scale_img, check_version, check_anchor_order, initialize_weights, \
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\comic_text_detector\utils\yolov5_utils.py", line 4, in <module>
    import pkg_resources as pkg
ModuleNotFoundError: No module named 'pkg_resources
'`

**Comment by Interlinked** [comment]
Try using pip install --upgrade setuptools before running mokuro

**Comment by novastar88** [comment]
Working perfect, thank you.
